#+title: About
#+date: <2024-08-17 08:57>
#+filetags: computers emacs blog
#+ATTR_HTML: :border 2 :rules all :frame border

** whoami
Hello there! You can call me Henrique.
The main purpose of this website is to share some interesting things I find on the world wide web and the projects of mine.
Some of the stuff I work on [[https://github.com/0xhenrique][Github]].

** My Computers
*** ThinkPad T480
- OS: GNU Guix
- DE: EXWM/XFCE4
- CPU: Intel i5-8350U (8) @ 3.600GHz
- GPU: 😕
- RAM: 24Gb

*** Xeon PC
- OS: GNU Guix
- DE: EXWM/XFCE4
- CPU: Intel Xeon E5-2650 v4 (24) @ 2.900GHz 
- GPU: AMD ATI Radeon 540/540X/550/550X / RX 540X/550/550X 
- Memory: 32GB

** Keyboards
*** The Charybdis by Bastard Keyboards
https://i.imgur.com/vqbSpXX.jpeg
Right now I'm using the Charybdis. It simply feels "correct" to type with it.  
The only _drawback_ from this keyboard is the price, but I don't think you will find a dactyl for a cheap price.  
As far as I know, there's no company mass producing that type of keyboard.  
But at the end I think it's worth it, at least for me it is.

*** The Sofle V1 by Mechboards UK
https://i.imgur.com/O4zYPni.jpeg
The other one I have (although don't use very much anymore) is the Sofle V1 that I bought from Mechboards UK.
It was very nice to type on a _low profile_ keyboard. It's not so expansive as the Charybdis.
