#+title: Nazare Beach
#+date: <2024-08-17 08:57>
#+filetags: travel photography portugal
#+ATTR_HTML: :border 2 :rules all :frame border

I visited Nazaré Beach last year (2023). Such a lovely place.
Shame on me for not taking my camera with me that day. I'm not a fan of smartphone cameras to be honest. Still, I couldn't let the opportunity pass. Here are some photos I took that day.

https://i.imgur.com/ATjnpyl.jpeg

According to Wikipedia, Nazaré is one of the most traditional Portuguese fishing villages, having the most popular bathing beach on the Portuguese west coast, where you can still find, on the sand, some women dressed in the traditional costume of seven skirts, taking care of the fish that dries in the sun, lined up on stakes.

https://i.imgur.com/GwZIh3p.jpeg

I plan to go back there in the winter, but this time I will remember to take my camera with me. I have an 18-55 and a 200mm, but I believe I will get better photos with the 200mm, especially in the higher parts. Not to mention that I will be able to aim further without losing too much sharpness.

https://i.imgur.com/hxY0rcS.jpeg
https://i.imgur.com/8uRNHtF.jpeg
