#+title: With or without AI, we all lose
#+date: <2025-03-17 08:57>
#+filetags: ai economy
#+ATTR_HTML: :border 2 :rules all :frame border

Antes de tudo, gostaria de dizer que o intuito deste artigo não é dar minha opinião sobre se programadores serão substituídos por IA, mas sim para mostrar que a qualidade de vida no geral vai piorar bastante. Essa piora poderá se dar tanto pelos avanços da IA quanto pela derrocada das democracias liberais. De uma forma ou de outra, não temos outra opção senão nos prepararmos para o pior.

Se não tiver paciência ou tiver pouco tempo para gastar aqui, recomendo que leia a conclusão do artigo e decida se vale ou não a pena continuar. Muito do que falarei aqui será referenciado de outros blogs, portais de notícias, estudos acadêmicos, livros etc, o que pode resultar num volume bem grande de texto. Então esteja ciente de que não será uma leitura fácil e muito menos prazerosa.

Caso encontre algum erro no meu artigo ou queira discutir sobre o assunto, deixarei as minhas informações de contato ao final do artigo. No mais, desejo uma boa leitura e espero que meu texto sirva agregue de forma positiva na sua vida.

* O jogo está fraudado desde o início
Já fazem alguns anos que governos ao redor de todo o mundo praticam algo conhecido como "Juros Negativos". Movimento que parece ser interessante quando visto de forma raza, mas que revela grandes problemas quando começamos a mexer no vespeiro. O Banco Central Europeu, por exemplo praticou uma taxa de juros negativa durante mais de uma década, com o objetivo de estancar o sangramento causado pela crise de 2008-09.

De modo grosseiro, isso significa que o Banco Central do seu país passa a cobrar dos bancos comerciais por manterem reservas excedentes. A intenção é estimular que as pessoas consumam mais e invistam mais, em detrimento das pessoas que poupam dinheiro. Caso você ainda não tenha percebido, isso é literalmente o Estado praticando roubo. Essa política monetária resultou em trilhões de dólares em títulos com rendimentos literalmente negativos, especialmente durante períodos de crise econômica, como a crise de 2008 e a pandemia de COVID-19. Mais uma vez, se você não percebeu ainda: você está sendo roubado!

* O avanço da tecnologia permite que o governo te roube cada vez mais
Ao artificialmente injetar dinheiro falso na economia, o efeito esperado é que os preços aumentem para se adaptar à nova base monetária expandida, mas na prática não vemos isso acontecer, pelo menos não de forma consequencial. Por exemplo, se consultar o M2 Americano entre 2020 e 2025, vai ver que houve um aumento de 40% no total supply, mas isso não resultou automaticamente num aumento proporcional dos preços. O motivo disso é muito simples: avanço tecnológico e ganho de produtividade. Cada ano que passa, é possível produzir mais com menos custo.

Imagine o custo que havia embutido numa simples batata na prateleiro de um supermercado 20 anos atrás, agora imagine hoje em dia, com o processo quase totalmente automatizado, máquinas mais baratas, mais eficientes, menos trabalhadores nos campos, engenharia genética para que as batatas cresçam mais rápido etc. Uma batata hoje deveria ter um valor marginal quase simbólico, mas na prática isso não aconteceu. Todo o ganho de produtividade e eficiência foram completamente sabotados pelas práticas criminosas dos governos.

No sistema financeiro atual, os governos aproveitam essa eficiência "criando" mais dinheiro, diluindo o valor do dinheiro que já está nas suas mãos. Mas, em vez de mostrar isso às claras, ajustam apenas os preços nos índices oficiais (popularmente conhecidos como taxa de inflação).

Em outras palavras, o governo passa a "lucrar" por ter o monopólio da emissão de moeda. Se não percebeu, vou falar mais uma vez: você está sendo roubado.

* Em que vale a pena ainda investir
Se a taxa de juros é negativa, qualquer investimento que você faça resultará negativo no longo prazo. Não importa se é ouro, ações, bonds, commodities, etc. No melhor cenário você vai apenas "empatar" com o aumento da base monetária, mas será virtualmente impossível ter lucro real, pelo menos não de forma honesta. Mesmo no ano em que você conseguir diluir o roubo estatal, nada garantirá que no próximo ano você não perderá.
Para exemplificar, vou usar como exemplo os EUA, por serem a maior economia do mundo, além do dólar ter valor real muito maior que qualquer outra moeda por conta do Paradoxo de Triffin.
[https://i.imgur.com/A84Ad9P.png]
Você, cidadão Americano, que começou a investir seu suado salário a partir de 2018, saiba que o FED e seus lacaios, diluíram a sua riqueza em aproximadamente 400% em apenas 7 anos. Algo em torno de 57% ao ano. Algum investimento que você fez nesse período resultou em pelo menos 57% de lucro anuais? Se não, lamento lhe informar mais uma vez: você foi roubado.

Começou a investir antes disso? Que tal traçarmos o aumento da base monetária desde 2005 até 2025? São duas décadas da sua vida investindo, certo? Com certeza você deve estar no lucro! Vejamos:
[https://i.imgur.com/iZMiRL8.png]

Bom, parece que não. Eu duvido muito que algum investimento seu tenha te retornado de forma regular 56% ao ano durante essas duas décadas que passaram.
Quer dizer, a quantidade de dígitos talvez tenha aumentado, mas durante essas duas décadas a tecnologia avançou imensamento em níveis sem precedentes, mas parece que todo o ganho de produtividade foi pro ralo pois o governo achou de bom grado foder com a vida de todos os poupadores para estimular o consumo. Ao invés de juntar dinheiro para comprar uma casa à vista, agora o governo te força a contrair um empréstimo e basicamente vender o resto do seu tempo de vida.

Então fica a questão, por que economizar dinheiro, investir à longo prazo se, afinal de contas, o governo vai se aproveitar do ganho de produtividade da população para diluir nossas riquezas?

* Você está financiando a sua própria falha
Uma vez que a maior parte do dinheiro dos bancos simplesmente não existe, pois é gerado a partir da aberração que é o juro negativo, quantitative easing e promoção de títulos podres, quem termina financiando a existência de bancos é o próprio cidadão que trabalha. Quando alguma empresa de IA receber um aporte bilionário de algum banco para investir em tecnologias para te substituir, saiba que foi você que financiou tudo isso. Obviamente de maneiro não consensual, o que só piora o cenário.
É como se você estivesse literalmente trabalhando para financiar uma empresa que te quer na sarjeta.
Se eles vão conseguir ou não atingir o objetivo de construir a AGI e substituir você, não é relevante para o meu ponto. Conseguindo atingir o objetivo ou não, eles saem ganhando e você sai perdendo. Eles ficam mais ricos enquanto que você fica mais pobre.
Mas nós somos seres humanos, afinal de contas. Não seria a primeira vez que financiamos algo para destruir a nós mesmos. Lembre-se que no século passado bilhões de dólares foram investidos para construir bombas atômicas com poder de destruição em massa. Armas biológicas foram pesquisadas em laboratórios do governo, etc. 
Agora some isso tudo à influência que os lunáticos do Fórum Econômico Mundial têm sob os governos de todo o mundo e você tem uma força global trabalhando 24h por dia para te destruir financeira, moral e espiritualmente.

* Privacidade é coisa do passado

