name: Deploy to Neocities

# Only run on changes to the main branch
on:
  push:
    branches:
      - master

concurrency: # Prevent concurrent deploys doing strange things
  group: deploy-to-neocities
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
    # Step 1: Check out the repository
    - uses: actions/checkout@v4

    # Step 2: Set up Hugo (this downloads and installs Hugo)
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v3
      with:
        hugo-version: '0.119.0'

    # Step 3: Build the Hugo site
    - name: Build the Hugo site
      run: hugo --minify

    # Step 4: Deploy the 'public' folder to Neocities
    - name: Deploy to Neocities
      uses: bcomnes/deploy-to-neocities@v2.0.2
      with:
        api_token: ${{ secrets.NEOCITIES_SECRET }} # Your Neocities API token stored as a secret
        cleanup: false
        dist_dir: public # The Hugo output folder
